<!-- The base of the code was generated by ChatGPT and I made adjustments as needed -->

<div class="container">
  <h2>Submit Additional Information</h2>
  <form action="{formaction 'path-to-endpoint'}" method="POST">
    
    <div class="form-group">
      <label for="fname">First Name:</label>
      <input type="text" id="fname" name="fname" class="form-control" required>
    </div>

    <div class="form-group">
      <label for="lname">Last Name:</label>
      <input type="text" id="lname" name="lname" class="form-control" required>
    </div>

    <div class="form-group">
      <label for="phone">Phone Number:</label>
      <input type="tel" id="phone" name="phone" class="form-control" placeholder="123-456-7890" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" required>
      <small>Format: 123-456-7890</small>
    </div>
    
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" id="email" name="email" class="form-control" required>
    </div>
    
    <div class="form-group">
      <label for="Allergies">Allergies:</label>
      <textarea id="allergies" name="allergies" class="form-control" required></textarea>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
